# ---------------------------- GENERAL SETTINGS ----------------------------
name: gym_tracker
description: "A simple app to track gym progress and results, developed with Flutter and Android Studio."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.2.0+2

environment:
  sdk: ^3.10.0


# isar version
# isar_version: &isar_version 3.3.2 # define the version to be used

# ----------------------------PACKAGES AND VERSIONS ----------------------------

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions consider running `flutter pub upgrade --major-versions`. 
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  markdown_widget: ^2.3.2

  # Create and manage workout data with a database structure
  isar_community: 
    version: 3.3.2 
    # version: *isar_version
  isar_community_flutter_libs: # contains Isar Core
    version: 3.3.2 
    # version: *isar_version

  # manage path
  path_provider: ^2.1.5
  file_picker: ^10.3.10

  # graphs
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^6.0.0
  dart_pubspec_licenses: ^3.0.14
  rename: ^3.1.0

  isar_community_generator: 
    version: 3.3.2
    # version: *isar_version

  build_runner: ^2.4.13

# to create automatically all icons
  flutter_launcher_icons: ^0.14.4

# to create starting logo when opening the app
  flutter_native_splash: ^2.4.0

# ---------------------------- FLUTTER PACKAGES ----------------------------
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - THIRD_PARTY_LICENSES.md

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# ---------------------------- OTHER PACKAGES ----------------------------
flutter_launcher_icons:
  android: true
  ios: true
  # base ikimage for old devices
  image_path: "assets/icons/logo_total_light.png" 
  
  # --- ADAPTIVE (Android) ---
  # Light theme
  adaptive_icon_background: "assets/icons/logo_bkg_light.png"
  adaptive_icon_foreground: "assets/icons/logo_subject_light.png"
  
  # Dark theme (Android 13+ and theme-icons)
  monochrome_white_icon: "assets/icons/logo_subject_dark.png"

flutter_native_splash:
  # --- LIGHT THEME ---
  color: "#FFFFFF" # bkg color
  image: "assets/icons/logo_subject_light.png"
  
  # --- DARK THEME ---
  color_dark: "#000000" # bkg color
  image_dark: "assets/icons/logo_subject_dark.png"
  fullscreen: false

  # extra options for centering
  android_12:
    image: "assets/icons/logo_subject_light.png"
    icon_background_color: "#FFFFFF"
    image_dark: "assets/icons/logo_subject_dark.png"
    icon_background_color_dark: "#000000"