#!/bin/bash

# NOTE: this script is BASH, use Linux terminal, on Windows use WSL or GIT BASH terminal 

# This script analyzes the 'oss_licenses.dart' file generated by 'dart_pubspec_licenses'
# and extracts all unique SPDX license identifiers to check compatibility.

LICENSE_FILE="oss_licenses.dart"

if [ ! -f "$LICENSE_FILE" ]; then
    echo "Error: File not found."
    echo "Make sure '$LICENSE_FILE' is in the current folder."
    echo "To generate the file, try the 'dart_pubspec_licenses' package: https://pub.dev/packages/dart_pubspec_licenses"
    exit 1
fi

echo "🔎 Analyzing unique license types in $LICENSE_FILE..."
echo "---"

# Finds packages where the spdxIdentifiers list is empty (spdxIdentifiers: [],)
PACKAGES_MISSING_SPDX=$(
    # Trova le linee che contengono 'spdxIdentifiers: []' o 'spdxIdentifiers: [],'
    # Utilizza -B 4 per includere il nome del pacchetto nella ricerca
    #grep 'spdxIdentifiers: \[\]' "$LICENSE_FILE"
    grep -E 'spdxIdentifiers: \[\].*' "$LICENSE_FILE" -B 6 2>/dev/null
)
# print the names
if [ -n "$PACKAGES_MISSING_SPDX" ]; then
    echo "! ATTENTION: The following packages DO NOT have an SPDX license identifier defined (spdxIdentifiers: [])."
    echo "These licenses must be MANUALLY CHECKED for compatibility, as they might be restrictive:"
    echo ""
    echo "$PACKAGES_MISSING_SPDX"
    echo ""
fi
echo ""
echo "---"
# make the analysis
grep "spdxIdentifiers:" "$LICENSE_FILE" | \
    # 1. Extracts the content within the square brackets '[...]'
    sed -E 's/.*\[(.*)\].*/\1/g' | \
    # 2. Removes single quotes ('), spaces, and leftover square brackets
    tr -d " '[]" | \
    # 3. Replaces all commas with a new line to separate identifiers
    tr ',' '\n' | \
    # 4. Removes any resulting blank lines
    grep -v '^$' | \
    # 5. Sorts and displays only the unique licenses (removing duplicates)
    sort | uniq

echo "---"
echo "✅ Analysis complete."